version: "3"

services:
  node:
    image: node:16
    container_name: roleplay
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3001:3001 # API port
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password # mysql password for container
      MYSQL_HOST: db

  db:
    container_name: roleplay_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306 # mysql container port 1
      - 33060:33060 # mysql container port 2
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: roleplay_net
